trigger:
  paths:
    include: # Hmm, this repeats the list of CLI dependencies
      - api
      - cli
      - serialization

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: Build CLI
    jobs:
      - job: Build
        displayName: Build CLI
        steps:
          - task: Gradle@3
            inputs:
              workingDirectory: $(Build.SourcesDirectory)
              tasks: :cli:build
